"""
Search Router - API endpoints for document search.

This router provides endpoints for:
- Lexical search using PostgreSQL full-text search
- Dense search using vector similarity (T02)
- Hybrid search with RRF fusion (T03)

Endpoints:
    GET /lexical - Lexical search using ts_vector/ts_query
    GET /dense - Dense search using pgvector similarity
"""

import logging
import time
from fastapi import APIRouter, HTTPException, Query, status
from sqlalchemy.exc import SQLAlchemyError

from vulcanlab.data.database import get_session
from vulcanlab.search.search_lexical import search_lexical
from vulcanlab.search.search_dense import search_dense
from vulcanlab.search.search_hybrid import search_hybrid
from vulcanlab_api.schemas.search import (
    LexicalSearchResponse,
    DenseSearchResponse,
    HybridSearchResponse,
    SearchResult,
    DenseSearchResult,
    HybridSearchResult,
    PaginationInfo,
    RRFStats
)

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get(
    "/lexical",
    response_model=LexicalSearchResponse,
    status_code=status.HTTP_200_OK,
    summary="Lexical search",
    description="Search chunks using PostgreSQL full-text search (ts_vector/ts_query). "
                "Results are ranked by ts_rank relevance score. "
                "Includes breadcrumb trails and bibliographic metadata.",
    responses={
        200: {
            "description": "Search results with pagination",
            "model": LexicalSearchResponse
        },
        400: {
            "description": "Invalid query parameters"
        },
        500: {
            "description": "Internal server error during search"
        }
    }
)
async def lexical_search(
    q: str = Query(
        ...,
        min_length=1,
        description="Search query (keywords separated by spaces)",
        example="cognitive psychology memory"
    ),
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed)",
        example=1
    ),
    page_size: int = Query(
        default=20,
        ge=1,
        le=100,
        description="Number of results per page (max 100)",
        example=20
    ),
    headings_only: bool = Query(
        default=False,
        description="If true, only search heading chunks (H1-H5)",
        example=False
    ),
    top_k: int = Query(
        default=20,
        ge=1,
        le=1000,
        description="Maximum total results to consider (default: 20)",
        example=20
    )
) -> LexicalSearchResponse:
    """
    Lexical search using PostgreSQL full-text search.

    Searches chunk content using PostgreSQL's to_tsvector and to_tsquery.
    Results are ranked by ts_rank for relevance.
    Includes breadcrumb trails (generated by traversing hierarchy to H1)
    and bibliographic metadata (work title, authors, year).

    Args:
        q: Search query (keywords)
        page: Page number (default: 1)
        page_size: Results per page (default: 20, max: 100)
        headings_only: Only search H1-H5 chunks (default: False)
        top_k: Maximum total results (default: 20, max: 1000)

    Returns:
        LexicalSearchResponse with results and pagination info

    Raises:
        400: Invalid query parameters
        500: Database error during search
    """
    # Validate query
    if not q or not q.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query parameter 'q' cannot be empty"
        )

    # Log search parameters
    logger.info(
        f"Lexical search request: query='{q}', page={page}, "
        f"page_size={page_size}, headings_only={headings_only}"
    )

    try:
        start_time = time.time()

        with get_session() as session:
            # Call core search function
            results, total_count = search_lexical(
                query=q.strip(),
                session=session,
                page=page,
                page_size=page_size,
                headings_only=headings_only,
                top_k=top_k
            )

            # Map results to response model
            search_results = [
                SearchResult(
                    id=r["id"],
                    content_preview=r["content_preview"],
                    breadcrumb=r["breadcrumb"],
                    level=r["level"],
                    work_id=r["work_id"],
                    work_title=r["work_title"],
                    work_authors=r["work_authors"],
                    work_year=r["work_year"],
                    start_line=r["start_line"],
                    end_line=r["end_line"],
                    rank_score=r["rank_score"]
                )
                for r in results
            ]

            # Calculate pagination info
            has_next = (page * page_size) < total_count
            has_prev = page > 1

            pagination = PaginationInfo(
                page=page,
                page_size=page_size,
                total_results=total_count,
                has_next=has_next,
                has_prev=has_prev
            )

            elapsed_time = time.time() - start_time
            logger.debug(
                f"Lexical search completed in {elapsed_time:.3f}s: "
                f"{total_count} total results, returned page {page}"
            )

            return LexicalSearchResponse(
                results=search_results,
                pagination=pagination
            )

    except ValueError as e:
        # Invalid parameters from core function
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except SQLAlchemyError as e:
        # Database error
        logger.error(f"Database error during lexical search: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database error during search: {str(e)}"
        )
    except Exception as e:
        # Generic error
        logger.error(f"Unexpected error during lexical search: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred during search: {str(e)}"
        )


@router.get(
    "/dense",
    response_model=DenseSearchResponse,
    status_code=status.HTTP_200_OK,
    summary="Dense search",
    description="Search chunks using pgvector dense similarity (cosine distance). "
                "Query is embedded using same model as RAG retrieval. "
                "Results are ranked by semantic similarity. "
                "Includes breadcrumb trails and bibliographic metadata.",
    responses={
        200: {
            "description": "Search results with pagination",
            "model": DenseSearchResponse
        },
        400: {
            "description": "Invalid query parameters"
        },
        500: {
            "description": "Internal server error during search or embedding generation"
        }
    }
)
async def dense_search(
    q: str = Query(
        ...,
        min_length=1,
        description="Search query (will be embedded for semantic similarity)",
        example="cognitive processes in memory"
    ),
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed)",
        example=1
    ),
    page_size: int = Query(
        default=20,
        ge=1,
        le=100,
        description="Number of results per page (max 100)",
        example=20
    ),
    headings_only: bool = Query(
        default=False,
        description="If true, only search heading chunks (H1-H5)",
        example=False
    ),
    top_k: int = Query(
        default=20,
        ge=1,
        le=1000,
        description="Maximum total results to consider (default: 20)",
        example=20
    )
) -> DenseSearchResponse:
    """
    Dense search using pgvector similarity.

    Generates embedding for query text using same model as RAG retrieval,
    then searches chunks using pgvector's cosine distance operator.
    Results are ranked by semantic similarity (1 - distance).
    Includes breadcrumb trails (generated by traversing hierarchy to H1)
    and bibliographic metadata (work title, authors, year).

    Args:
        q: Search query (will be embedded)
        page: Page number (default: 1)
        page_size: Results per page (default: 20, max: 100)
        headings_only: Only search H1-H5 chunks (default: False)
        top_k: Maximum total results (default: 20, max: 1000)

    Returns:
        DenseSearchResponse with results and pagination info

    Raises:
        400: Invalid query parameters
        500: Database error or embedding generation failure
    """
    # Validate query
    if not q or not q.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query parameter 'q' cannot be empty"
        )

    # Log search parameters
    logger.info(
        f"Dense search request: query='{q}', page={page}, "
        f"page_size={page_size}, headings_only={headings_only}"
    )

    try:
        start_time = time.time()

        with get_session() as session:
            # Call core search function
            results, total_count = search_dense(
                query=q.strip(),
                session=session,
                page=page,
                page_size=page_size,
                headings_only=headings_only,
                top_k=top_k
            )

            # Map results to response model
            search_results = [
                DenseSearchResult(
                    id=r["id"],
                    content_preview=r["content_preview"],
                    breadcrumb=r["breadcrumb"],
                    level=r["level"],
                    work_id=r["work_id"],
                    work_title=r["work_title"],
                    work_authors=r["work_authors"],
                    work_year=r["work_year"],
                    start_line=r["start_line"],
                    end_line=r["end_line"],
                    similarity_score=r["similarity_score"]
                )
                for r in results
            ]

            # Calculate pagination info
            has_next = (page * page_size) < total_count
            has_prev = page > 1

            pagination = PaginationInfo(
                page=page,
                page_size=page_size,
                total_results=total_count,
                has_next=has_next,
                has_prev=has_prev
            )

            elapsed_time = time.time() - start_time
            logger.debug(
                f"Dense search completed in {elapsed_time:.3f}s: "
                f"{total_count} total results, returned page {page}"
            )

            return DenseSearchResponse(
                results=search_results,
                pagination=pagination
            )

    except ValueError as e:
        # Invalid parameters from core function
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except RuntimeError as e:
        # Embedding generation or other runtime error
        logger.error(f"Runtime error during dense search: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )
    except SQLAlchemyError as e:
        # Database error
        logger.error(f"Database error during dense search: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database error during search: {str(e)}"
        )
    except Exception as e:
        # Generic error
        logger.error(f"Unexpected error during dense search: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred during search: {str(e)}"
        )


@router.get(
    "/hybrid",
    response_model=HybridSearchResponse,
    status_code=status.HTTP_200_OK,
    summary="Hybrid search",
    description="Search chunks using hybrid lexical and dense fusion (RRF). "
                "Combines keyword matching and semantic similarity. "
                "Parameters for RRF fusion are configurable.",
    responses={
        200: {
            "description": "Fined search results with RRF scores",
            "model": HybridSearchResponse
        },
        400: {
            "description": "Invalid query parameters"
        },
        500: {
            "description": "Internal server error"
        }
    }
)
async def hybrid_search(
    q: str = Query(
        ...,
        min_length=1,
        description="Search query",
        example="cognitive architecture"
    ),
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    headings_only: bool = Query(default=False),
    rrf_k: int = Query(default=60, ge=1, description="RRF smoothing constant"),
    dense_top_k: int = Query(default=20, ge=1, le=100, description="Dense candidates to fetch"),
    lexical_top_k: int = Query(default=20, ge=1, le=100, description="Lexical candidates to fetch"),
    dense_weight: float = Query(default=0.5, gt=0, description="Weight for dense results"),
    lexical_weight: float = Query(default=0.5, gt=0, description="Weight for lexical results")
) -> HybridSearchResponse:
    """
    Hybrid search combining lexical and dense results via RRF.
    """
    if not q or not q.strip():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query parameter 'q' cannot be empty"
        )

    logger.info(
        f"Hybrid search request: query='{q}', page={page}, "
        f"rrf_k={rrf_k}, dense_w={dense_weight}, lexical_w={lexical_weight}"
    )

    try:
        start_time = time.time()

        with get_session() as session:
            results, rrf_stats_data, total_count = search_hybrid(
                query=q.strip(),
                session=session,
                page=page,
                page_size=page_size,
                headings_only=headings_only,
                rrf_k=rrf_k,
                dense_top_k=dense_top_k,
                lexical_top_k=lexical_top_k,
                dense_weight=dense_weight,
                lexical_weight=lexical_weight
            )

            # Map results to response model
            search_results = [
                HybridSearchResult(
                    id=r["id"],
                    content_preview=r["content_preview"],
                    breadcrumb=r["breadcrumb"],
                    level=r["level"],
                    work_id=r["work_id"],
                    work_title=r["work_title"],
                    work_authors=r["work_authors"],
                    work_year=r["work_year"],
                    start_line=r["start_line"],
                    end_line=r["end_line"],
                    rrf_score=r["rrf_score"],
                    dense_rank=r["dense_rank"],
                    lexical_rank=r["lexical_rank"]
                )
                for r in results
            ]

            # Calculate pagination info
            has_next = (page * page_size) < total_count
            has_prev = page > 1

            pagination = PaginationInfo(
                page=page,
                page_size=page_size,
                total_results=total_count,
                has_next=has_next,
                has_prev=has_prev
            )

            rrf_stats = RRFStats(**rrf_stats_data)

            elapsed_time = time.time() - start_time
            logger.debug(f"Hybrid search completed in {elapsed_time:.3f}s")

            return HybridSearchResponse(
                results=search_results,
                pagination=pagination,
                rrf_stats=rrf_stats
            )

    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))
    except (RuntimeError, SQLAlchemyError) as e:
        logger.error(f"Error during hybrid search: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))
    except Exception as e:
        logger.error(f"Unexpected error during hybrid search: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="An error occurred during search")
