-- Add citation columns to works table
ALTER TABLE works ADD COLUMN IF NOT EXISTS volume VARCHAR(50);
ALTER TABLE works ADD COLUMN IF NOT EXISTS issue VARCHAR(50);
ALTER TABLE works ADD COLUMN IF NOT EXISTS pages VARCHAR(50);
ALTER TABLE works ADD COLUMN IF NOT EXISTS edition VARCHAR(50);
ALTER TABLE works ADD COLUMN IF NOT EXISTS url VARCHAR(1000);
ALTER TABLE works ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE works ADD COLUMN IF NOT EXISTS institution VARCHAR(255);
ALTER TABLE works ADD COLUMN IF NOT EXISTS editor VARCHAR(1000);
