site_name: VulcanLab
site_description: VulcanLab v0.3.0
docs_dir: src                   # Source markdown files are in docs/src/
site_dir: site                  # Build output goes to docs/site/
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - ts
    - js
  logo: img/logo-sm.png
  favicon: img/favicon.ico
nav:
  - Home: index.md
  - Getting Started:
    - getting-started.md
    - Docker Setup: docker_setup.md
    - Running Locally: running_locally.md
  - Guide:
    - VulcanLab Pages: pages/index.md
    - Using CLI: cli_docs/cli_overview.md
repo_url: https://github.com/DominikGorecki/vulcanlab
edit_uri: edit/main/docs/src/